# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be87695610e7ee59bfa1f05937cb7846ce2acab798b10ff242cce9300c529a5874dd34d17b3367210090c1dfb21011df18efcce9f4784153128b1496cc89d76a

test:
  secret_key_base: 4a6c5d5f4b91e3efe0be71a787f81a0df3d1c0832a1c6e12c035b78d35b2a482cd6b4805a88557255c039d53b2d5a13a99d11d273b8be8e35953bb2a416e7038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
